In [93]:
## KNN Classification Algorithm (K = hyperparameters => set by us humans)
### Predict class (label) based on buying,maint,door,persons,lug_boot,safety features

from sklearn import preprocessing
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing

In [94]:
data = pd.read_csv("car.data", sep=",")
data.head()

buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc

In [95]:
##coverting non numerical to numeric : Getting data to correct form

le = preprocessing.LabelEncoder()
buying = le.fit_transform(list(data["buying"]))
maint = le.fit_transform(list(data["maint"]))
door = le.fit_transform(list(data["door"]))
persons = le.fit_transform(list(data["persons"]))
lug_boot = le.fit_transform(list(data["lug_boot"]))
safety = le.fit_transform(list(data["safety"]))
cls = le.fit_transform(list(data["class"]))



In [96]:
X = list(zip(buying, maint, door, persons, lug_boot, safety))  # features (datapoints)
Y = list(cls)  # labels (predict)


In [97]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size = 0.2)


In [98]:
model = KNeighborsClassifier(n_neighbors=9) #hyperparameter (highest acc = 9)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [99]:
acc = model.score(x_test, y_test)
print(acc)

0.9219653179190751


In [100]:
predicted = model.predict(x_test)
names = ["unacc", "acc", "good", "vgood"]

for x in range(len(predicted)):
    print("Predicted: ", names[predicted[x]], "Data: ", x_test[x], "Actual: ", names[y_test[x]])


Predicted:  good Data:  (0, 3, 1, 0, 1, 1) Actual:  good
Predicted:  good Data:  (3, 3, 2, 0, 1, 2) Actual:  good
Predicted:  unacc Data:  (0, 0, 0, 2, 0, 0) Actual:  unacc
Predicted:  good Data:  (0, 2, 0, 0, 0, 2) Actual:  good
Predicted:  good Data:  (0, 2, 3, 1, 0, 1) Actual:  good
Predicted:  good Data:  (0, 0, 3, 2, 2, 1) Actual:  good
Predicted:  good Data:  (1, 3, 1, 2, 1, 2) Actual:  unacc
Predicted:  good Data:  (1, 3, 1, 1, 0, 1) Actual:  good
Predicted:  good Data:  (0, 2, 2, 0, 0, 2) Actual:  good
Predicted:  good Data:  (1, 2, 0, 1, 1, 2) Actual:  unacc
Predicted:  good Data:  (1, 2, 1, 0, 2, 0) Actual:  good
Predicted:  good Data:  (0, 0, 0, 1, 0, 1) Actual:  good
Predicted:  good Data:  (3, 0, 0, 2, 0, 2) Actual:  good
Predicted:  good Data:  (1, 2, 0, 0, 0, 1) Actual:  good
Predicted:  good Data:  (1, 2, 0, 1, 0, 2) Actual:  acc
Predicted:  good Data:  (3, 0, 4, 2, 1, 2) Actual:  good
Predicted:  good Data:  (1, 1, 0, 0, 2, 2) Actual:  good
Predicted:  unacc Data:  (2,

In [101]:
for x in range(len(predicted)):
    print("Predicted: ", names[predicted[x]], "Data: ", x_test[x], "Actual: ", names[y_test[x]])
    n = model.kneighbors([x_test[x]], 9, True)
    print("N: ", n)

Predicted:  good Data:  (0, 3, 1, 0, 1, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 1.41421356, 1.41421356]]), array([[ 348, 1169,  322, 1014, 1257,   91,  773, 1275, 1318]],
      dtype=int64))
Predicted:  good Data:  (3, 3, 2, 0, 1, 2) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[1371,  225,  576,  525,  917,  731,  970,  443, 1055]],
      dtype=int64))
Predicted:  unacc Data:  (0, 0, 0, 2, 0, 0) Actual:  unacc
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[ 434,  301, 1028,  612, 1024, 1175,  963,  138,  391]],
      dtype=int64))
Predicted:  good Data:  (0, 2, 0, 0, 0, 2) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.41421356,
        1.41421356, 1.41421356, 1.41421356, 1.414

N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 1.41421356, 1.41421356]]), array([[ 120, 1116,  846, 1366,  480,   17,  649, 1035,  852]],
      dtype=int64))
Predicted:  unacc Data:  (3, 1, 3, 1, 1, 0) Actual:  unacc
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 256,  609,  103,  633, 1148,  627,  828,  151, 1242]],
      dtype=int64))
Predicted:  good Data:  (1, 2, 1, 0, 1, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 202,  848,  702,  611,   21, 1257,  508,  615,  667]],
      dtype=int64))
Predicted:  good Data:  (1, 2, 0, 2, 1, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.41421356, 1.41421356]]), array([[ 404,  221, 1333, 1078,  857,  933,   4

N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 221,  615,  332,  137,  849,  429,  667, 1315,  829]],
      dtype=int64))
Predicted:  good Data:  (2, 0, 1, 1, 0, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.41421356,
        1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[   5,  867,  394, 1196, 1203,  727, 1290,  419, 1349]],
      dtype=int64))
Predicted:  good Data:  (1, 0, 3, 1, 2, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 790,  582,  545,  407,  689,  136, 1031,  644,  209]],
      dtype=int64))
Predicted:  good Data:  (3, 3, 0, 0, 0, 1) Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[1114, 1125, 1134,  766,  349,  620,  782,

In [102]:
##Support Vector Machine
### ADD Z AXIS like => kernel (hyperplane) x1,x2,x3
import sklearn
from sklearn import svm
from sklearn import datasets

In [103]:
cancer = datasets.load_breast_cancer() ##get data from sklearn lib

In [104]:
print("Features: ", cancer.feature_names)
print("Labels: ", cancer.target_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']


In [105]:
X = cancer.data #features
Y = cancer.target #labels

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X,Y,test_size = 0.2)

In [106]:
print("X train val:" , x_train)
print("Y train val:" , y_train)

X train val: [[1.287e+01 1.954e+01 8.267e+01 ... 6.384e-02 3.313e-01 7.735e-02]
 [9.436e+00 1.832e+01 5.982e+01 ... 5.052e-02 2.454e-01 8.136e-02]
 [1.115e+01 1.308e+01 7.087e+01 ... 5.506e-02 2.859e-01 6.772e-02]
 ...
 [1.221e+01 1.802e+01 7.831e+01 ... 8.829e-02 3.218e-01 7.470e-02]
 [1.793e+01 2.448e+01 1.152e+02 ... 1.136e-01 2.504e-01 7.948e-02]
 [1.625e+01 1.951e+01 1.098e+02 ... 1.775e-01 3.318e-01 9.136e-02]]
Y train val: [1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1
 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 0 1 0 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0
 0 1 1 1 1 1 0 1 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1
 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1
 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1
 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1
 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 1 

In [128]:
from sklearn import metrics
classes = ["malignant", "benign"]

clf = svm.SVC(kernel = "linear", C=2)
clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

acc = metrics.accuracy_score(y_test,y_pred)
print(acc)

0.9649122807017544


In [129]:
clf2 = KNeighborsClassifier(n_neighbors=9)
clf2.fit(x_train,y_train)

y_pred = clf2.predict(x_test)

acc2 = metrics.accuracy_score(y_test,y_pred)
print(acc2)

0.9122807017543859


In [130]:
diff = acc - acc2
diffP = diff * 100
print("svm difference (margin) with KNN: ", diffP , "%")

svm difference (margin) with KNN:  5.263157894736848 %
